[workspace]
members = [
    "common",
    "btc_on_int",
    "int_on_eos",
    "int_on_evm",
    "eos_on_int",
    "int_on_algo",
    "erc20_on_int",
]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
lto = "thin"
overflow-checks = true
