[package]
license = "MIT"
publish = false
edition = "2018"
version = "4.17.0"
readme = "README.md"
name = "ptokens_core"
keywords = ["provable", "defi", "crypto"]
authors = ["Provable Things <provable.xyz>", "Greg Kapka <greg@oraclize.it>"]

[features]
debug = []
non-validating = ["debug"]

[profile.release]
lto = "thin"
overflow-checks = true

[dependencies]
hex = "0.4.2"
log = "0.4.14"
rlp = "0.5.0"
rand = "0.8.3"
chrono = "0.4.19"
ethabi = "13.0.0"
byteorder = "1.4.2"
rustc-hex = "2.1.0"
simplelog = "0.9.0"
serde_json = "1.0.62"
lazy_static = "1.4.0"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
# upgrade blocked by ethabi
ethereum-types = "0.10.0"
serde = { version = "1.0.123", features = ["derive"] }
bitcoin = { version = "0.26.0", features = ["use-serde", "rand"] }
eos-chain = { git = "https://github.com/bifrost-finance/rust-eos" }
secp256k1 = { git = "https://github.com/bifrost-finance/rust-secp256k1", features = ["recovery", "rand-std"] }
quick-error = "2.0.0"
derive_more = "0.99.11"

[dev-dependencies]
simple_logger = "1.11.0"
