[workspace]
members = [
    "common/eos",
    "common/fees",
    "common/common",
    "common/bitcoin",
    "common/loggers",
    "common/vanilla",
    "common/metadata",
    "common/algorand",
    "common/ethereum",
    "common/chain_ids",
    "common/enclave_info",
    "v3_bridges/sentinel",
    "common/debug_signers",
    "common/database_utils",
    "common/safe_addresses",
    "common/ethereum_debug",
    "v2_bridges/btc_on_int",
    "v1_bridges/btc_on_eos",
    "v1_bridges/btc_on_eth",
    "v1_bridges/eos_on_eth",
    "v2_bridges/int_on_eos",
    "v2_bridges/int_on_evm",
    "v2_bridges/eos_on_int",
    "v2_bridges/int_on_algo",
    "common/rocksdb_database",
    "v1_bridges/erc20_on_evm",
    "v1_bridges/erc20_on_eos",
    "v2_bridges/erc20_on_int",
]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
lto = "thin"
overflow-checks = true
