[workspace]
members = [
    "common",
    "v2_bridges/btc_on_int",
    "v2_bridges/int_on_eos",
    "v2_bridges/int_on_evm",
    "v2_bridges/eos_on_int",
    "v2_bridges/int_on_algo",
    "v2_bridges/erc20_on_int",
]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
lto = "thin"
overflow-checks = true
