[core]
max_cancellable_time_delta = 15 # How far out of a sync a chain can be before we no longer allow cancelling of user ops on it
timeout = 30 # How long in seconds to wait before giving up when making core calls

[native]
eth_chain_id = "947"
pnetwork_hub = "0xc508e6af23d3C1FcAbD24Dfab5A5304F65c0042c"
endpoints = [ "" ]
sleep_duration = 5 # How long to wait before trying to get the next host block (in seconds)
contract_addresses = [] # Used to prefilter submission material to reduce total batch size.
validate = false # Used to turn off validation for this side's chain.
gas_limit = 1
gas_price = 2 # NOTE: If this is omitted, and rpc call will be made to determine the gas price from the node
batch_size = 500 # Max number of blocks to batch together before submitting to core
batch_duration = 60 # Max amount of time (in seconds) between batch submissions
pre_filter_receipts = true # Pre filter receipts in app before submitting to the core

[host]
eth_chain_id = "42161"
pnetwork_hub = "0x578E916A4064c32F2eF44614Ff9B04B6D2546A13"
endpoints = [ "" ]
sleep_duration = 1 # How long to wait before trying to get the next native block (in seconds)
contract_addresses = [] # Used to prefilter submission material to reduce total batch size.
validate = false # Used to turn off validation for this side's chain.
gas_limit = 1
gas_price = 2 # NOTE: If this is omitted, and rpc call will be made to determine the gas price from the node
pre_filter_receipts = true # Pre filter receipts in app before submitting to the core

[batching]
host_batch_size = 500 # Max number of host blocks to batch together before submission
native_batch_size = 10 # Max number of native blocks to batch together before submission
host_batch_duration = 60 # Max amount of time between batch submission in seconds
native_batch_duration = 60 # Max amount of time between batch submission in seconds

[log]
level = "debug"
enabled = true # Allow logging to be turned off entirely if desired
use_file_logging = false # If false, logs are written to stderr, if true, logs are written to file
path = "./" # Path to write logs to. Defaults to "./"
max_num_logs = 10 # Maximum number of logs to maintain. The oldest half are compressed.
max_log_size = 1_000_000_000 # Maximum size of a single log in bytes. Defalt is 10mb

[ipfs]
status_update_frequency = 120 # How often to publish status updates
ipfs_bin_path = "" # Path to the ipfs binary on your system

[governance]
mcid = "polygon" # Chain on which the governance contract lives
address = "0xc508e6af23d3C1FcAbD24Dfab5A5304F65c0042c" # Governance contract address
