[native]
chain_id = "EthereumMainnet"
endpoints = [ "ws://162.19.83.219:8546" ]
sleep_time = 15 # How long to wait before trying to get the next host block (in seconds)
contract_addresses = [] # Used to prefilter submission material to reduce total batch size.

[host]
chain_id = "EthereumMainnet"
endpoints = [ "ws://162.19.83.219:8546" ]
sleep_time = 15 # How long to wait before trying to get the next native block (in seconds)
contract_addresses = [] # Used to prefilter submission material to reduce total batch size.

[batching]
host_batch_size = 5 # Max number of host blocks to batch before submission
native_batch_size = 10 # Max number of native blocks to batch before submission
host_batch_duration = 300 # Max amount of time between batch submission in seconds
native_batch_duration = 300 # Max amount of time between batch submission in seconds

[log]
level = "debug"
use_file_logging = false # If false, logs are written to stderr, if true, logs are written to file
path = "./" # Path to write logs to. Defaults to "./"
max_num_logs = 10 # Maximum number of logs to maintain. The oldest half are compressed.
max_log_size = 1_000_000 # Maximum size of a single log in bytes. Defalt is 10mb

[mongo]
database = "database"
collection = "reports"
uri = "mongodb://127.0.0.1:27017"
