[database]
db_path = "./database_gnosis_arbitrum"

[log]
level = "debug"
enabled = true # Allow logging to be turned off entirely if desired
use_file_logging = false # If false, logs are written to stderr, if true, logs are written to file
path = "./" # Path to write logs to. Defaults to "./"
max_num_logs = 10 # Maximum number of logs to maintain. The oldest half are compressed.
max_log_size = 1_000_000_000 # Maximum size of a single log in bytes. Defalt is 10mb
