[package]
name = "peos-on-int"
version = "2.0.3"
authors = ["gregkapka <greg@oraclize.it>"]
edition = "2021"
rust-version = "1.56"

[features]
file-logger = ["common_file_logger"]
default = ["rocks-db", "file-logger"]
rocks-db = ["common_rocksdb_database"]
json-rpc-db = ["common_jsonrpc_database"]
std-err-logger = ["common_stderr_logger"]
non-validating = ["common/non-validating", "eos_on_int/non-validating"]

[dependencies]
log = "0.4.14"
paste = "1.0.7"
docopt = "1.1.1"
anyhow = "1.0.69"
serde = { version = "1.0.130", features = ["derive"] }

eos_on_int = { path = "../../eos_on_int" }
common = { path = "../../../common/common" }
common_docopt_macros = { package = "docopt_macros", path = "../../../common/docopt_macros" }
common_file_logger = { package = "file_logger", path = "../../../common/file_logger", optional = true }
common_stderr_logger = { package = "stderr_logger", path = "../../../common/stderr_logger", optional = true }
common_rocksdb_database = { package = "rocksdb_database", path = "../../../common/rocksdb_database", optional = true }
common_jsonrpc_database = { package = "jsonrpc_database", path = "../../../common/jsonrpc_database", optional = true }
