[package]
license = "MIT"
publish = false
edition = "2021"
version = "1.0.2"
readme = "README.md"
rust-version = "1.56"
name = "safe_addresses"
keywords = ["provable", "defi", "crypto"]
authors = ["Greg Kapka <gregkapka@gmail.com>"]

[dependencies]
log = "0.4.14"
lazy_static = "1.4.0"
ethereum-types = "0.12.1"
rust-algorand = { workspace = true }
bitcoin = { version = "0.29.2", features = ["serde", "rand"] }
eos-chain = { git = "https://github.com/bifrost-finance/rust-eos", rev = "8e57843" }

common = { path = "../common" }

[lib]
doctest = false
