[package]
edition = "2021"
version = "1.0.1"
rust-version = "1.56"
name = "stderr_logger"
authors = ["Greg Kapka <gregkapka@gmail.com>"]

[dependencies]
stderrlog = { workspace = true }

common = { workspace = true }

[lib]
doctest = false
