[package]
edition = "2021"
version = "1.0.0"
rust-version = "1.56"
name = "rocksdb_database"
authors = ["Greg Kapka <gregkapka@gmail.com>"]

[dependencies]
hex = "0.4.3"
log = "0.4.14"
rocksdb = "0.17.0"
quick-error = "2.0.1"
common = { package = "common", path = "../common" }
