[package]
edition = "2021"
version = "2.0.3"
name = "pint-on-algo"
rust-version = "1.56"
authors = ["Greg Kapka <gregkapka@gmail.com>"]

[features]
file-logger = ["common_file_logger"]
default = ["rocks-db", "file-logger"]
rocks-db = ["common_rocksdb_database"]
json-rpc-db = ["common_jsonrpc_database"]
std-err-logger = ["common_stderr_logger"]
non-validating = ["int_on_algo/non-validating"]

[dependencies]
log = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }

int_on_algo = { path = "../../int_on_algo" }

common = { workspace = true }
common_docopt_macros = { workspace = true }
common_file_logger = { workspace = true, optional = true }
common_stderr_logger = { workspace = true, optional = true }
common_rocksdb_database = { workspace = true, optional = true }
common_jsonrpc_database = { workspace = true, optional = true }
