[package]
version = "2.0.1"
edition = "2021"
name = "peos-on-eth"
rust-version = "1.56"
authors = ["gregkapka <gregkapka@gmail.com>"]

[features]
file-logger = ["common_file_logger"]
default = ["rocks-db", "file-logger"]
rocks-db = ["common_rocksdb_database"]
json-rpc-db = ["common_jsonrpc_database"]
std-err-logger = ["common_stderr_logger"]
disable-fees = ["eos_on_eth/disable-fees"]
non-validating = ["eos_on_eth/non-validating"]

[dependencies]
log = { workspace = true }
serde = { workspace = true }
paste = { workspace = true }
docopt = { workspace = true }
anyhow = { workspace = true }

eos_on_eth = { path = "../../eos_on_eth" }

common = { workspace = true }
common_docopt_macros = { workspace = true }
common_file_logger = { workspace = true, optional = true }
common_stderr_logger = { workspace = true, optional = true }
common_rocksdb_database = { workspace = true, optional = true }
common_jsonrpc_database = { workspace = true, optional = true }
