[package]
version = "1.0.1"
edition = "2021"
rust-version = "1.56"
name = "docopt_macros"
authors = ["Greg Kapka <gregkapka@gmail.com>"]

[dependencies]
docopt = { workspace = true }
common = { workspace = true }

[lib]
doctest = false
