[package]
version = "1.0.0"
edition = "2021"
rust-version = "1.56"
name = "docopt_macros"
authors = ["Greg Kapka <gregkapka@gmail.com>"]

[dependencies]
docopt = "1.1.1"
common = { path = "../common" }

[lib]
doctest = false
